# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go 
description: |
  Running ubuntu-latest, this action builds the artifact on 1.21.x, tests and 
  then publishes the json results in an artifact to TestResults.json

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go 1.21.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install Dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Testing with Go CLI
      run: go test -json > TestResults.json

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results
        path: TestResults.json
